import logging
import io
import os
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib import colors
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

logger = logging.getLogger(__name__)

def generate_formatted_draft_pdf(content: str) -> bytes:
    """Generate a properly formatted legal PDF from text content using ReportLab"""
    try:
        # 1. Register Fonts (Mukta supports both Latin and Devanagari)
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        font_regular_path = os.path.join(base_dir, 'assets', 'fonts', 'Mukta-Regular.ttf')
        font_bold_path = os.path.join(base_dir, 'assets', 'fonts', 'Mukta-Bold.ttf')

        if not os.path.exists(font_regular_path):
            logger.error(f"Font not found: {font_regular_path}")
            # Fallback to standard fonts if Mukta is missing
            font_name = "Helvetica"
            font_bold_name = "Helvetica-Bold"
        else:
            pdfmetrics.registerFont(TTFont('Mukta', font_regular_path))
            pdfmetrics.registerFont(TTFont('Mukta-Bold', font_bold_path))
            font_name = 'Mukta'
            font_bold_name = 'Mukta-Bold'

        # 2. Setup Document
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )

        styles = getSampleStyleSheet()
        
        # Custom Styles
        title_style = ParagraphStyle(
            'LegalTitle',
            parent=styles['Normal'],
            fontName=font_bold_name,
            fontSize=16,
            alignment=TA_CENTER,
            spaceAfter=20,
            textTransform='uppercase'
        )
        
        body_style = ParagraphStyle(
            'LegalBody',
            parent=styles['Normal'],
            fontName=font_name,
            fontSize=11,
            leading=16,
            alignment=TA_JUSTIFY,
            spaceAfter=12
        )
        
        footer_style = ParagraphStyle(
            'LegalFooter',
            parent=styles['Normal'],
            fontName=font_name,
            fontSize=9,
            alignment=TA_CENTER,
            textColor=colors.grey,
            spaceBefore=30
        )

        # 3. Build Story
        story = []
        
        # Header
        story.append(Paragraph("LEGAL DOCUMENT", title_style))
        story.append(HRFlowable(width="100%", thickness=2, color=colors.black, spaceAfter=20))
        
        # Content
        paragraphs = content.split('\n\n')
        for p_text in paragraphs:
            if p_text.strip():
                # Clean up text for XML-based Paragraph
                safe_text = p_text.strip().replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
                safe_text = safe_text.replace('\n', '<br/>')
                story.append(Paragraph(safe_text, body_style))
        
        # Footer
        story.append(Spacer(1, 40))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey, spaceBefore=20))
        story.append(Paragraph(
            "This document is generated by LegalSahayak AI. Please verify with a legal professional before use.",
            footer_style
        ))
        
        # 4. Generate PDF
        doc.build(story)
        return buffer.getvalue()

    except Exception as e:
        logger.error(f"Draft PDF generation error: {str(e)}")
        import traceback
        logger.error(traceback.format_exc())
        return b""
